from .alerts_page import AlertsPage
from .login_page import LoginPage
from .navigation_page import NavigationPage
from .nested_views_page import NestedViewsPage
from .web_page import WebPage
from .base_pages.tab_view_page import TabViewPage
from .base_pages.base_page import BasePage
from .inputs.date_selector_page import DateSelectorPage
from .native.video_player_page import VideoPlayerPage
from .native.image_gallery_page import ImageGalleryPage
